apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-api-app-deployment
spec:
  selector:
    matchLabels:
      app: cloud-api-app
  replicas: 2
  template:
    metadata:
      labels:
        app: cloud-api-app #for service
    spec:
      containers:
      - name: cloud-api-app
        image: cloud-api-app:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
